project_id = "ssmxmfcophjtaltldkcx"

[functions.pacientes-search]
verify_jwt = false

[functions.paciente]
verify_jwt = false

[functions.paciente-vacinas]
verify_jwt = false

[functions.vacina-detalhe]
verify_jwt = false
